### ISSUE TITLE
withXXX functions do not free memory if action throws exception

### ISSUE THREAD

**Issue by rethab** [rethab/h-gpgme#1]
All the 'withXXX' do not free the previously allocated memory if the action throws an exception.

**Comment by dmp1ce** [comment]
@rethab Did you have a way to reproduce this? How did you determine that there is a memory leak?

**Comment by rethab** [comment]
Take a look at this:

```haskell
withCtx homedir localeStr prot f = do
    ctx <- newCtx homedir localeStr prot
    res <- f ctx
    freeCtx ctx
return res
```

Now `f` is a user - supplied function. If that function throws an exception, then `freeCtx` is never run.
