### ISSUE TITLE
"Left NoData" is returned when attempting decryption of symmetrically-encrypted data

### ISSUE THREAD

**Issue by adinapoli** [rethab/h-gpgme#11]
Hi!

I'm trying to use your library to decrypt some emacs-gpg-encryped files. Emacs uses symmetrical encryption. This simple program return `Left NoData`:

``` haskell
{-# LANGUAGE OverloadedStrings #-}
module Main where

import qualified Data.ByteString as BS
import Crypto.Gpgme

withPassphraseCb :: String -> Ctx -> IO ()
withPassphraseCb passphrase ctx = do
      setPassphraseCallback ctx (Just callback)
  where
        callback _ _ _ = return (Just passphrase)

main :: IO ()
main = do
  secret <- BS.readFile "/my-path-to/secrets.org.gpg"
  dec <- withCtx "/Users/adinapoli/.gnupg" "C" OpenPGP $ \aCtx -> do
    withPassphraseCb "my-secret" aCtx
    decrypt aCtx secret
  print dec
```

Any clue on how I can troubleshoot this issue further?

Thanks!

Alfredo

**Comment by rethab** [comment]
Hi Alfredo,
I am assuming you have already checked the manual if there's a description about this error code? (https://www.gnupg.org/documentation/manuals/gpgme.pdf)

Do you consistently get this error message also when encrypting different data? Have you tried if h-pgpgme works on your machine with data that has been encrypted with gpg directly?

- Reto

**Comment by adinapoli** [comment]
Hey,

I've checked the manual but a quick `ctrl + f` does not reveal anything meaningful. I haven't tried anything different other than the attached example. If you want I can try to run the testsuite of the project and see if that works on my machine - I guess that would be a start :wink:

**Comment by rethab** [comment]
Can you decrypt the file with gpg directly?

**Comment by adinapoli** [comment]
I guess so - Cannot say anything about calling "gpg" directly, as I decrypt is directly inside Emacs:

http://orgmode.org/worg/org-tutorials/encrypting-files.html

When opening that file with Emacs, it prompts me for the passphrase and shows me the decrypted text:

![screen shot 2015-07-05 at 17 50 12](https://cloud.githubusercontent.com/assets/442035/8512348/5954beb4-233e-11e5-83ab-cb826df8b26a.png)

![screen shot 2015-07-05 at 17 50 25](https://cloud.githubusercontent.com/assets/442035/8512349/5e49db7a-233e-11e5-88a9-21373d022778.png)

**Comment by rethab** [comment]
Well I don't know anything about that emacs plugin. I'd suggest to try it with plain gpg in order to narrow the posssible causes down.

- Reto
