### ISSUE TITLE
Plaintext signing

### ISSUE THREAD

**Issue by dmp1ce** [rethab/h-gpgme#14]
Is there a way to do plaintext signing with this project? I saw signing with the encrypt function but what if I only want to sign and not encrypt?

**Comment by rethab** [comment]
There is not as of now. However this being essentially a wrapper around gpgme -- which does support it [1] -- adding it would probably be trivial.

- Reto

1. https://www.gnupg.org/documentation/manuals/gpgme/Encrypting-a-Plaintext.html

**Comment by joeyh-purism** [comment]
I also need plaintext signing in my potential use of this library.
