### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by nd2s** [rethab/h-gpgme#22]
Maybe I'm blind, but I only see functions taking strict `ByteString`s as input. Can this module be used to encrypt gigabyte-sized files via some kind of stream?

**Comment by dmp1ce** [comment]
I'm not aware of anything functions for encrypting a gigabyte-sized file. I'm happy to merge in streaming support if you want to work on it.

**Comment by nd2s** [comment]
I'm afraid this is a bit too much for me now. I saw that there is a `p'gpgme_data_new_from_stream` function as well as `p'gpgme_data_new_from_fd` in `Bindings.Gpgme` (the source repository linked from hackage is gone btw), but integrating that would require wide-ranging knowledge about both the C and the Haskell library. 

This would also mean writing a lazy version of **all** the current encryption/decryption functions. (I'm not sure the strict ones would even be needed at that point.)

**Comment by dmp1ce** [comment]
That sounds right. I have mostly used the `c'` functions so `c'gpgme_data_new_from_stream` might be easier to use. Also, make sure to read the gpgme documentation. https://www.gnupg.org/documentation/manuals/gpgme/File-Based-Data-Buffers.html#index-gpgme_005fdata_005fnew_005ffrom_005fstream

There is also information about large file support https://www.gnupg.org/documentation/manuals/gpgme/Largefile-Support-_0028LFS_0029.html#Largefile-Support-_0028LFS_0029

**Comment by dmp1ce** [comment]
@nd2s I'm looking into this issue now. BTW, the `Bindings.Gpgme` source is not gone, it has just been moved to Github. https://github.com/jwiegley/bindings-dsl

**Comment by dmp1ce** [comment]
Checkout my stream encryption test for encrypting from a stream. Let me know if you have any problems.

https://github.com/rethab/h-gpgme/blob/master/test/CryptoTest.hs#L213
