### ISSUE TITLE
Suppress prompts in tests where possible

### ISSUE THREAD

**Issue by dmp1ce** [rethab/h-gpgme#41]
Several tests prompt the user for a passphrase or confirmation. For many tests, this is not necessary and prevents the tests from being tested by Travis. Many of the tests that prompt for passphrases should be able to be suppressed by a passphrase callback, but I'm not sure how to suppress confirmation prompts.

See this issue for why suppressing the delete prompts is not currently possible: https://bugs.gnupg.org/gnupg/issue2916

**Comment by rethab** [comment]
This seems now supported (see link in description), but we first need to extend https://github.com/jwiegley/bindings-dsl to include the new `gpgme_op_delete_ext` function. I hope I can get a PR in there soon-ish and hopefully someone takes a look at it :)
