### ISSUE TITLE
Get the public key as a String

### ISSUE THREAD

**Issue by Ulrar** [rethab/h-gpgme#44]
Hi,

I need to get the public key as a String (to send all the needed public keys to a client for encryption) in armored format.

`getKey` returns a `Key`, and I don't see any method to convert that into anything else, not even a Show instance. Am I missing something, or is this just impossible ?

**Comment by rethab** [comment]
Hi @Ulrar,

no, this is not implemented in h-gpgme. If gpgme supports it, you are welcome to submit a PR. However looking at the documentation[1], I can see how to read the fingerprint (see chapter _7.5.1. Key objects_), but not the entire key.

- Reto

1. https://www.gnupg.org/documentation/manuals/gpgme.pdf

**Comment by Ulrar** [comment]
I'm guessing `7.5.7 Exporting Keys` is the way to do it, at least `gpg --export` is how I'm getting the pubkey by hand.

`gpgme_op_export(ctx, fingerprint, 0, keydata);`, not sure I understand what they mean about how to get it in armored form, though

**Comment by Ulrar** [comment]
Well, I tried but I just don't get it. I never tried to use a C library in haskell before, and I just don't understand how to use this gpgme_data_t, it seems like you need to allocate it, allocate a separate buffer somewhere then read from one to the other using `gpgme_data_read` .. That's too complicated for me, I'll just store the public keys in text files
